### ISSUE TITLE
Upload analysis zip not working when it contains execution-config.json file

### ISSUE THREAD

**Issue by ablack3** [OHDSI/Arachne#98]
When I upload a zip file that contains a file execution-config.json the upload seems to not work. When I remove that json file it does work.

I'm using the latest release of arachne and execution engine

Steps to reproduce: 

Create a new folder called `test-execution-config`

In that folder put an R script called main.R that contains one line of R code `print('it works')`

Also add a json file called `execution-config.json` with the following content

```
{
    "analysisName": "Simvastatin",
    "analysisType": "CUSTOM",
    "runtimeEnvironmentName": "Darwin Runtime",
    "dockerRuntimeEnvironmentImage": "executionengine.azurecr.io/darwin-base:v0.3" 
    "entryPoint": "test-execution-config/main.R",
    "studyName": "My study"
}
```

zip the folder an upload it to Arachne as a new analysis. 

I see that the application does not respond at all. There is no error or message. 

<img width="702" alt="image" src="https://github.com/user-attachments/assets/2f266577-3195-4226-98f5-a6e29a667c7f">

Expected behavior:
Fields should be auto populated with the values in the json file. If there is a problem with the format of the execution config file then some kind of message or instructions should be shown to the user describing how to fix the problem.

**Comment by konstjar** [comment]
`zip the folder an upload it to Arachne as a new analysis.`

It's supposed that metadata file is place in the root of archive, not in subfolder

**Comment by konstjar** [comment]
[ArachneTest-execution-config-main.zip](https://github.com/user-attachments/files/17378182/ArachneTest-execution-config-main.zip)
@SergeySukhanov  The metadata is not populated as expected

**Comment by konstjar** [comment]
The problem is in formatting.
<img width="739" alt="image" src="https://github.com/user-attachments/assets/c8fca991-42c9-4240-a703-b765e8a92d6c">
We need to handle and inform about errors in metadata files.

**Comment by konstjar** [comment]
Resolved in https://github.com/OHDSI/Arachne/pull/99

**Comment by ablack3** [comment]
Hi @konstjar,

I still don't see this feature working properly. It had been a while since I tested it. 

Here is the metadata.json file

```
{
    "analysisName": "Simvastatin 99",
    "analysisType": "CUSTOM",
    "runtimeEnvironmentName": "Darwin Runtime",
    "dockerRuntimeEnvironmentImage": "executionengine.azurecr.io/darwin-base:v0.1",
    "entryPoint": "main.R",
    "studyName": "My study 3"
}
```

I zip this in a folder and upload it to Arachne. I can see that some of the fields are populated correctly but the dockerRuntimeEnvironmentImage and entryPoint are not populated. Not a show stopper because we can just instruct the data partners which to use but it would be good if these were populated. 


Here is what I see when I upload the zipped folder. 

<img width="699" alt="Image" src="https://github.com/user-attachments/assets/b12e1659-e7de-4bd2-840b-01930f179787" />


Here are the versions I'm using in the dockerfile.


    image: odysseusinc/arachne-datanode-ce:2.0.4-DEV
    image: odysseusinc/execution_engine:2.7.0-SNAPSHOT


Do you have an example to show that the dockerRuntimeEnvironmentImage and the entryPoint can be populated?

**Comment by YaroslavTir** [comment]
Hi  @ablack3 

### **entryPoint**  
Are you sure the entry point name is correct? It's case-sensitive, so if your script in the ZIP is `Main.R`, it has to be exactly the same in `metadata.json` / `execution-config.json`.  

### **dockerRuntimeEnvironmentImage**  
The available Docker runtime images should be pre-populated, so check if your image name matches what’s in `metadata.json` / `execution-config.json`.  
From what I see, this is part of the Docker Execution Engine config:  
```bash
-e DOCKER_IMAGE_DEFAULT=dist  
-e DOCKER_IMAGE_FILTER="dist(.+)"  
```  
So the name should fit that pattern.  

I use pretty much the same test archive as you. Here’s an example I’ve used:  

**execution-config.json**  
```json
{
  "analysisName": "Hello World Test",
  "analysisType": "CUSTOM",
  "runtimeEnvironmentName": "Test Runtime",
  "dockerRuntimeEnvironmentImage": "dist_ohdsi",
  "entryPoint": "main.R",
  "studyName": "Example"
}
```  

**main.R**  
```r
print("Hello, World!")
```  

Let me know if that helps!

**Comment by konstjar** [comment]
To be confirmed by @ablack3 on RC version

**Comment by ablack3** [comment]
It is working now yes. Thank you!
